In [117]:
import pandas as pd
import numpy as np

In [118]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


In [120]:
# how many fuel types are present?
df['fuel_type'].nunique()

2

In [121]:
# how many columns have missing values
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [122]:
df['num_cylinders'].isnull().sum()

np.int64(482)

In [123]:
cols_nulls = 0

for col in df:
      if  df[col].isnull().sum() > 0:
          cols_nulls += 1

print(f"There are {cols_nulls} columns in the dataset that contain null values")


There are 4 columns in the dataset that contain null values


In [124]:
print(f"There are {cols_nulls} columns in the dataset that contain null values")

There are 4 columns in the dataset that contain null values


In [125]:
col_null = []

for col in df:
    if df[col].isnull().sum() >0:
        col_null.append(col)

print(f"These columns contain null values = {col_null}")

These columns contain null values = ['num_cylinders', 'horsepower', 'acceleration', 'num_doors']


In [126]:
cols_null_count = (df.isnull().sum()>0).sum()
cols_null_count

np.int64(4)

In [127]:
cols_with_nulls = df.columns[df.isnull().any()].tolist()
cols_with_nulls

['num_cylinders', 'horsepower', 'acceleration', 'num_doors']

In [128]:
df['origin'].unique()

array(['Europe', 'USA', 'Asia'], dtype=object)

In [129]:
#What's the maximum fuel efficiency
df_asia = df[df['origin']=='Asia']
df_asia['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [130]:
df['horsepower'].mean()

np.float64(149.65729212983547)

In [131]:
mode_hp = df['horsepower'].mode()
print(mode_hp)

0    152.0
Name: horsepower, dtype: float64


In [132]:
df['horsepower'] = pd.to_numeric(df['horsepower'], errors = 'coerce')
df['horsepower'] = df['horsepower'].fillna(mode_hp)

In [133]:
df['horsepower'].mean()

np.float64(149.65729212983547)

In [142]:
df_asia_2 = df_asia[['vehicle_weight', 'model_year']].reset_index(drop=True)
df_asia_2 = df_asia_2[:7]
df_asia_2

vehicle_weight  model_year
0     2714.219310        2016
1     2783.868974        2010
2     3582.687368        2007
3     2231.808142        2011
4     2659.431451        2016
5     2844.227534        2014
6     3761.994038        2019

In [143]:
X = df_asia_2.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [144]:
XTX = np.dot(X.T, X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [145]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [147]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [152]:
w = (XTX_inv.dot(X.T))*y
w

array([[-0.14432288, -0.11230828,  0.29810794, -0.36245398, -0.16251372,
        -0.06075771,  0.55811286],
       [ 0.28890053,  0.2560879 , -0.37871378,  0.59305003,  0.30835783,
         0.16679975, -0.72957556]])

In [153]:
total_w = np.sum(w)

In [154]:
total_w

np.float64(0.5187709081074016)